"""Tests for file generation, .zshrc sentinel idempotency, and reset."""

from __future__ import annotations

from welchost import detect, generator
from welchost.config import WelchostConfig


def test_generated_files_written(fake_home):
    cfg = WelchostConfig.default()
    zsh, banner = generator.write_generated_files(cfg)
    assert zsh.exists() and banner.exists()
    assert "welcome_banner.py" in zsh.read_text()
    assert "Generated by welchost" in banner.read_text()


def test_generated_banner_is_self_contained(fake_home):
    """The renderer must not import third-party packages at runtime."""
    cfg = WelchostConfig.default()
    _, banner = generator.write_generated_files(cfg)
    text = banner.read_text()
    assert "import rich" not in text
    assert "import pyfiglet" not in text
    assert "from rich" not in text


def test_gradient_direction_baked_into_banner(fake_home):
    cfg = WelchostConfig.default()
    cfg.banner.color_mode = "gradient"
    cfg.gradient.direction = "diagonal"
    _, banner = generator.write_generated_files(cfg)
    assert 'GRAD_DIR = "diagonal"' in banner.read_text()


def test_ornament_baked_and_renders(fake_home):
    cfg = WelchostConfig.default()
    cfg.banner.text = "Hi"
    cfg.ornament.name = "ghosts"
    _, banner = generator.write_generated_files(cfg)
    src = banner.read_text()
    assert "ORN_LEFT = " in src
    assert ")(" in src  # the ghost ornament glyphs are baked in
    # the generated script must execute without error
    ns = {"__name__": "not_main"}
    exec(compile(src, "welcome_banner.py", "exec"), ns)
    ns["render"]()


def test_sentinel_idempotent(fake_home):
    generator.inject_zshrc()
    generator.inject_zshrc()
    text = detect.get_zshrc().read_text()
    assert text.count(generator.SENTINEL_START) == 1
    assert text.count(generator.SENTINEL_END) == 1


def test_sentinel_contents(fake_home):
    generator.inject_zshrc()
    text = detect.get_zshrc().read_text()
    assert 'TERM_PROGRAM" == "ghostty"' in text
    assert "$- == *i*" in text
    # Robust Ghostty detection beyond TERM_PROGRAM (survives wrappers)…
    assert "GHOSTTY_RESOURCES_DIR" in text
    # …but suppressed inside a multiplexer so it doesn't reprint per pane.
    assert '-z "$TMUX"' in text
    assert '-z "$ZELLIJ"' in text


def test_inject_preserves_existing_content(fake_home):
    zshrc = detect.get_zshrc()
    zshrc.write_text("export FOO=bar\n")
    generator.inject_zshrc()
    text = zshrc.read_text()
    assert "export FOO=bar" in text
    assert generator.SENTINEL_START in text


def test_backup_created_when_zshrc_exists(fake_home):
    zshrc = detect.get_zshrc()
    zshrc.write_text("export FOO=bar\n")
    generator.inject_zshrc()
    backups = list(zshrc.parent.glob(".zshrc.welchost.bak.*"))
    assert backups, "expected a timestamped backup"


def test_remove_block_only_removes_sentinel(fake_home):
    zshrc = detect.get_zshrc()
    zshrc.write_text("export FOO=bar\n")
    generator.inject_zshrc()
    assert generator.remove_zshrc_block() is True
    text = zshrc.read_text()
    assert "export FOO=bar" in text
    assert generator.SENTINEL_START not in text


def test_remove_block_noop_without_sentinel(fake_home):
    detect.get_zshrc().write_text("export FOO=bar\n")
    assert generator.remove_zshrc_block() is False


def test_reset_removes_files_and_sentinel(fake_home):
    cfg = WelchostConfig.default()
    from welchost.config import save_config

    save_config(cfg)
    generator.install(cfg)
    assert detect.get_config_path().exists()
    removed = generator.reset()
    assert detect.get_config_path() in removed
    assert not detect.get_welcome_zsh_path().exists()
    assert not detect.get_welcome_banner_path().exists()
    assert generator.SENTINEL_START not in detect.get_zshrc().read_text()


def test_resolve_color_hex_and_name():
    assert generator.resolve_color("#ff0000") == (255, 0, 0)
    assert generator.resolve_color("#abc") == (170, 187, 204)
    assert generator.resolve_color("cyan") == generator.NAMED_COLORS["cyan"]
    assert generator.resolve_color("not-a-color") == (204, 204, 204)


def test_build_figlet_nonempty(fake_home):
    cfg = WelchostConfig.default()
    art = generator.build_figlet(cfg)
    assert art.strip()


def test_build_figlet_invalid_font_falls_back(fake_home):
    cfg = WelchostConfig.default()
    cfg.banner.font = "definitely-not-a-font"
    # Must not raise; falls back to the standard font.
    assert generator.build_figlet(cfg).strip()


def test_install_with_bad_font_does_not_half_write(fake_home):
    cfg = WelchostConfig.default()
    cfg.banner.font = "definitely-not-a-font"
    from welchost.config import save_config

    save_config(cfg)
    generator.install(cfg)
    assert detect.get_welcome_banner_path().exists()
    assert detect.get_welcome_zsh_path().exists()


def test_curated_fonts_are_all_valid():
    from welchost.tui.fonts import CURATED

    invalid = [f for f in CURATED if not generator.font_exists(f)]
    assert invalid == [], f"invalid curated fonts: {invalid}"
