"""Anonymous, **opt-in** usage analytics (PostHog).

Pure core (no TUI, no Textual). Nothing is sent until the user grants consent:
on first run the TUI shows a one-time prompt (via :func:`needs_consent_prompt`)
and records the answer with :func:`record_consent`. Thereafter the TUI calls
:func:`track_launch` from a background thread on launch, like the self-update
check, so the network call never blocks the UI. Everything here **fails soft** —
a missing key, an offline machine, or a malformed response must never break or
slow the app, so every public function swallows errors and returns a benign
default rather than raising.

Opt-in (rather than opt-out) is the GDPR/ePrivacy-safe posture for EU users: a
persistent device id is pseudonymous data, so we ask before storing or sending
it. The PostHog project is EU-hosted (see :data:`POSTHOG_HOST`).

What is and isn't sent
----------------------
We send a random, locally-generated UUID (``distinct_id``) plus coarse,
non-identifying facts: welchost version, install method, OS name/version, CPU
arch, and Python minor version. No usernames, paths, IPs, config contents, or
machine fingerprints. Person profiles are disabled on PostHog's side via the
``$process_person_profile`` property, so the UUID is never enriched into a
real-person record.

How to turn it off
------------------
Telemetry never sends unless the user opted in, and is disabled outright when
**any** of these hold:
- the embedded :data:`POSTHOG_API_KEY` is empty (the default — ships as a no-op);
- DEV mode is active (never phone home while hacking on the tool) — unless
  ``WELCHOST_TELEMETRY_FORCE`` is set, a hatch for exercising the prompt in dev;
- ``WELCHOST_NO_TELEMETRY`` is set to anything but empty/``0``;
- ``DO_NOT_TRACK`` (the cross-tool standard, consoledonottrack.com) is set.

A user who already opted in can stop sending at any time with the env vars above.
"""

from __future__ import annotations

import json
import os
import platform
import urllib.request
import uuid
from datetime import UTC, datetime
from pathlib import Path

from . import __version__, detect, net

# The PostHog *project* API key (a write-only "phc_..." key). We deliberately do
# NOT commit it to this public repo. It is resolved at import time, in order:
#   1. the WELCHOST_POSTHOG_KEY env var (for local testing / self-hosted forks);
#   2. a generated ``_secrets.py`` that CI bakes into the published artifact at
#      release time from a GitHub secret (see .github/workflows/release.yml).
# When neither is present (a plain source checkout), the key is empty and all
# telemetry below is a guaranteed no-op — so the repo ships dark and only the
# released package phones home.


def _resolve_api_key() -> str:
    key = os.environ.get("WELCHOST_POSTHOG_KEY", "")
    if key:
        return key
    try:
        from ._secrets import POSTHOG_API_KEY as baked  # generated by CI, gitignored

        return baked or ""
    except Exception:
        return ""


POSTHOG_API_KEY = _resolve_api_key()

# PostHog ingestion host. EU cloud (our project is EU-hosted); use
# "https://us.i.posthog.com" for a US project, or your self-hosted instance's URL.
POSTHOG_HOST = "https://eu.i.posthog.com"

# Network calls are best-effort and must never delay launch; keep this short.
TIMEOUT = 2.0


def _state_path() -> Path:
    """Sidecar file holding the anonymous distinct_id (never in welchost.toml)."""
    return detect.get_analytics_path()


def _env_set(name: str) -> bool:
    """True if env var ``name`` is set to anything other than empty/``0``."""
    return os.environ.get(name, "") not in ("", "0")


def is_configured() -> bool:
    """True if telemetry is *permitted* to run at all — independent of consent.

    Requires a key, a non-dev session, and neither opt-out env var. DEV mode
    disables it (don't phone home while hacking) unless WELCHOST_TELEMETRY_FORCE
    is set — that hatch exists only so the opt-in prompt can be exercised in dev.
    """
    if not POSTHOG_API_KEY:
        return False
    if detect.is_dev() and not _env_set("WELCHOST_TELEMETRY_FORCE"):
        return False
    if _env_set("WELCHOST_NO_TELEMETRY"):
        return False
    if _env_set("DO_NOT_TRACK"):
        return False
    return True


def is_enabled() -> bool:
    """True only if telemetry will actually send: configured AND the user has
    granted consent (opt-in). Never raises."""
    return is_configured() and consent_state() == "granted"


def _read_state() -> dict:
    """The parsed sidecar dict, or ``{}`` if absent/unreadable."""
    try:
        data = json.loads(_state_path().read_text())
        return data if isinstance(data, dict) else {}
    except (OSError, ValueError):
        return {}


def consent_state() -> str:
    """The persisted opt-in decision: ``"granted"`` | ``"declined"`` | ``"unset"``.

    ``"unset"`` means we have never asked (or the answer wasn't stored) — the
    only state in which the TUI prompts.
    """
    state = _read_state()
    if "consent" not in state:
        return "unset"
    return "granted" if state.get("consent") else "declined"


def needs_consent_prompt() -> bool:
    """True if telemetry is configured but the user hasn't decided yet — the
    signal for the TUI to show the one-time opt-in prompt. Never raises."""
    try:
        return is_configured() and consent_state() == "unset"
    except Exception:
        return False


def _properties() -> dict:
    """Coarse, non-identifying facts attached to every event."""
    from .update import detect_install_method

    try:
        install_method = detect_install_method()
    except Exception:
        install_method = "unknown"

    return {
        "$lib": "welchost",
        "$lib_version": __version__,
        # Keep PostHog from building a person profile around the anonymous UUID.
        "$process_person_profile": False,
        "welchost_version": __version__,
        "install_method": install_method,
        "os": platform.system().lower(),
        "os_version": platform.mac_ver()[0] or None,
        "arch": platform.machine(),
        "python": ".".join(platform.python_version_tuple()[:2]),
    }


def capture(event: str, distinct_id: str, props: dict | None = None) -> bool:
    """POST a single event to PostHog's capture endpoint. Returns success; never
    raises (any error → ``False``).

    ``props`` lets the caller pass a precomputed property dict so a multi-event
    flow (install + launch on first run) builds it once instead of re-running
    ``detect_install_method()`` per event. Defaults to a fresh ``_properties()``.
    """
    payload = {
        "api_key": POSTHOG_API_KEY,
        "event": event,
        "distinct_id": distinct_id,
        "timestamp": datetime.now(UTC).isoformat(),
        "properties": props if props is not None else _properties(),
    }
    try:
        req = urllib.request.Request(
            f"{POSTHOG_HOST.rstrip('/')}/capture/",
            data=json.dumps(payload).encode(),
            headers={
                "Content-Type": "application/json",
                "User-Agent": f"welchost/{__version__}",
            },
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=TIMEOUT, context=net.ssl_context()) as resp:  # noqa: S310
            return 200 <= resp.status < 300
    except Exception:
        return False


def record_consent(granted: bool) -> None:
    """Persist the user's opt-in decision (called once, after the prompt).

    On grant: mint the anonymous id if needed and send the first ``install`` +
    ``launch``. On decline: store the choice so we never ask or send again.
    No-ops when not configured. Never raises.
    """
    try:
        if not is_configured():
            return
        state = _read_state()
        distinct_id = state.get("distinct_id") or uuid.uuid4().hex
        now = datetime.now(UTC).isoformat(timespec="seconds")
        state.update({"distinct_id": distinct_id, "consent": bool(granted), "consent_at": now})
        state.setdefault("first_seen", now)
        try:
            detect.ensure_config_dir()
            _state_path().write_text(json.dumps(state))
        except OSError:
            # Can't persist (read-only dir): we'll re-prompt next launch, but
            # still honor this session's choice below.
            pass
        if granted:
            props = _properties()  # build once; reused across both events
            capture("install", distinct_id, props)
            capture("launch", distinct_id, props)
    except Exception:
        return


def track_launch() -> None:
    """Send a ``launch`` event on a normal (already-consented) start. No-ops
    unless telemetry is configured and consent was granted. Never raises."""
    try:
        if not is_enabled():
            return
        distinct_id = _read_state().get("distinct_id")
        if not distinct_id:
            return
        capture("launch", distinct_id, _properties())
    except Exception:
        return
