name: Homebrew Formula Test

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  test-brew:
    name: Test Homebrew install
    runs-on: macos-latest
    steps:
      - name: Test formula
        run: |
          brew tap scoobynko/welchost
          brew install welchost
          welchost version
          welchost doctor
